apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rp-status
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rp_status-rp-dashboard=rp_status-rp-dashboard
    argocd-image-updater.argoproj.io/rp_status-rp-dashboard.update-strategy: digest
    argocd-image-updater.argoproj.io/rp_status-rp-dashboard.force-update: "true"
    # argocd-image-updater.argoproj.io/write-back-method: git
    argocd.argoproj.io/refresh: hard
    argocd.argoproj.io/sync-options: Validate=false
    argocd.argoproj.io/sync-wave: "0"
    kubectl.kubernetes.io/restartedAt: '{{ now | date "2006-01-02T15:04:05Z07:00" }}'
spec:
  project: default
  source:
    repoURL: https://github.com/arsen3d/rp_status.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: lilypad
  syncPolicy:
    automated:
      prune: true  # Changed to true to ensure resources are properly managed
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Added for more controlled apply
      - FieldManager=argocd  # Control the field manager
      - IgnoreResourceVersion=true  # Ignore resource version differences
      - RespectIgnoreDifferences=false  # Ensures syncs occur despite ignored differences
      - ApplyOutOfSyncOnly=false  # Force apply on every sync
      - Replace=true  # Use replace instead of apply to ensure all resources are recreated
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: rp-dashboard
      namespace: lilypad
      jsonPointers:
        - /spec/selector
        - /spec/template/metadata/labels
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/initContainers
    - group: apps
      kind: Deployment
      name: rp-dashboard
      namespace: lilypad
      jqPathExpressions:
        - .spec.selector
