apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rp-status
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rp_status-rp-dashboard=rp_status-rp-dashboard
    argocd-image-updater.argoproj.io/rp_status-rp-dashboard.update-strategy: digest
    argocd-image-updater.argoproj.io/rp_status-rp-dashboard.force-update: "true"
    # argocd-image-updater.argoproj.io/write-back-method: git
    argocd.argoproj.io/refresh: hard
    argocd.argoproj.io/sync-options: Validate=false
    argocd.argoproj.io/sync-wave: "0"
    kubectl.kubernetes.io/restartedAt: '{{ now | date "2006-01-02T15:04:05Z07:00" }}'
spec:
  project: default
  source:
    repoURL: https://github.com/arsen3d/rp_status.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: lilypad
  syncPolicy:
    automated:
      # Enable automatic sync when Git repository changes are detected through polling
      prune: true      # Automatically delete resources that are no longer defined in Git
      selfHeal: true   # Automatically sync when drift is detected between Git and the cluster
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FieldManager=argocd
      - IgnoreResourceVersion=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - Validate=false
      - Replace=false
      - Force=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: rp-dashboard
      namespace: lilypad
      jsonPointers:
        - /spec/selector
        - /spec/template/metadata/labels
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/initContainers
    - group: apps
      kind: Deployment
      name: rp-dashboard
      namespace: lilypad
      jqPathExpressions:
        - .spec.selector
