apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rp-dashboard
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rp_status-rp-dashboard=rp_status-rp-dashboard
    argocd-image-updater.argoproj.io/rp_status-rp-dashboard.update-strategy: digest
    argocd-image-updater.argoproj.io/rp_status-rp-dashboard.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/arsen3d/rp_status.git  # Replace with your actual Git repository URL
    targetRevision: HEAD
    path: argocd
    plugin:
      name: argocd-build-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: lilypad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
