apiVersion: v1
kind: ConfigMap
metadata:
  name: build-info
  namespace: lilypad
  annotations:
    # This annotation will force ArgoCD to always update this resource
    argocd.argoproj.io/sync-options: Replace=true,Force=true
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"  # Run before other resources
data:
  # This will change only when commit hash changes
  git_commit: "{{.Values.git.revision}}"
  repo_url: "https://github.com/arsen3d/rp_status.git"
  # Current timestamp to force update on sync
  current_timestamp: "{{ now | date \"2006-01-02T15:04:05Z07:00\" }}"
