apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lilypad

resources:
- deployment.yaml
- service.yaml
# - ingress.yaml
# - tekton-pipeline.yaml
# - tekton-tasks.yaml
# - tekton-pipelinerun.yaml  # Cannot be used with kustomize due to generateName
# - argocd-build-plugin.yaml

# Remove labels entirely to avoid any potential problems with selectors
labels:
 - pairs:
     part-of: rp-status
     managed-by: argocd
   includeSelectors: false

configurations:
- kustomizeconfig.yaml
