apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lilypad

resources:
- deployment.yaml
- service.yaml
# - ingress.yaml
- tekton-pipeline.yaml
- tekton-tasks.yaml
# - tekton-pipelinerun.yaml  # Commented out as PipelineRuns are managed by the build plugin
- argocd-build-plugin.yaml

# Remove labels entirely to avoid any potential problems with selectors
# labels:
#  - pairs:
#      part-of: rp-status
#      managed-by: argocd
#    includeSelectors: false

configurations:
- kustomizeconfig.yaml
