apiVersion: v1
kind: Service
metadata:
  name: rp-dashboard-service
  namespace: lilypad
  labels:
    app: rp-dashboard-service
    app.kubernetes.io/instance: rp-status
    managed-by: argocd
spec:
  selector:
    app: rp-dashboard
  ports:
  - port: 8090
    targetPort: 80
    nodePort: 31090
  type: NodePort  # This is correct for Minikube environment
