apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-build-pipeline
  namespace: lilypad
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from
    - name: branch-name
      type: string
      description: The git branch to clone
      default: "main"
    - name: image-name
      type: string
      description: The name of the image to build
      default: "rp_status-rp-dashboard"
    - name: image-tag
      type: string
      description: The tag for the built image
      default: "latest"
    - name: registry-url
      type: string
      description: The Docker registry URL to push the image to
      default: "localhost:5000"
    - name: registry-user
      type: string
      description: The Docker registry username
      default: ""
    - name: registry-password
      type: string
      description: The Docker registry password
      default: ""
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
        apiVersion: tekton.dev/v1beta1
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
        - name: deleteExisting
          value: "true"
    - name: build-docker-image
      taskRef:
        name: docker-build-and-load
        kind: Task
        apiVersion: tekton.dev/v1beta1
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
        - name: context
          value: .
        - name: dockerfile
          value: ./Dockerfile
    - name: push-docker-image
      taskRef:
        name: docker-push
        kind: Task
        apiVersion: tekton.dev/v1beta1
      runAfter:
        - build-docker-image
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image-name
          value: $(params.image-name)
        - name: image-tag
          value: $(params.image-tag)
        - name: registry-url
          value: $(params.registry-url)
        - name: registry-user
          value: $(params.registry-user)
        - name: registry-password
          value: $(params.registry-password)
    - name: deploy-application
      taskRef:
        name: kubernetes-actions
        kind: Task
        apiVersion: tekton.dev/v1beta1
      runAfter:
        - push-docker-image
      params:
        - name: script
          value: |
            # Generate a timestamp for this deployment
            TIMESTAMP=$(date +%s)
            
            # Update deployment configuration to use registry image
            echo "Updating deployment configuration to use registry image..."
            REGISTRY_IMAGE="$(params.registry-url)/$(params.image-name):latest"
            sed -i "s|image:.*|image: ${REGISTRY_IMAGE}|g" ./argocd/deployment.yaml
            sed -i "s|imagePullPolicy:.*|imagePullPolicy: Always|g" ./argocd/deployment.yaml
            
            # Add a timestamp annotation to force redeployment
            echo "Adding timestamp annotation to deployment..."
            kubectl patch deployment rp-dashboard -n lilypad --type=json \
              -p="[{\"op\": \"replace\", \"path\": \"/metadata/annotations/tekton.dev~1lastBuilt\", \"value\": \"${TIMESTAMP}\"}]" || true
            
            # Create registry credentials if needed
            if [[ "$(params.registry-url)" != *"localhost"* && "$(params.registry-url)" != *"127.0.0.1"* ]]; then
              # For non-local registries
              if [ -n "$(params.registry-user)" ] && [ -n "$(params.registry-password)" ]; then
                echo "Creating registry credentials secret..."
                kubectl create secret docker-registry registry-credentials \
                  --docker-server=$(params.registry-url) \
                  --docker-username=$(params.registry-user) \
                  --docker-password=$(params.registry-password) \
                  --namespace=lilypad \
                  --dry-run=client -o yaml | kubectl apply -f -
              else
                echo "No registry credentials provided, creating empty one..."
                kubectl create secret docker-registry registry-credentials \
                  --docker-server=$(params.registry-url) \
                  --namespace=lilypad \
                  --dry-run=client -o yaml | kubectl apply -f -
              fi
            else
              echo "Using local registry, no credentials needed."
            fi
            
            # Apply the Kubernetes resources
            echo "Applying Kubernetes resources..."
            kubectl apply -k ./argocd/
            
            # Restart the deployment to ensure it picks up the new image
            echo "Restarting deployment..."
            kubectl rollout restart deployment rp-dashboard -n lilypad
            
            # Monitor rollout status
            echo "Monitoring rollout status..."
            kubectl rollout status deployment rp-dashboard -n lilypad --timeout=60s || true
