apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubernetes-actions
  namespace: lilypad
spec:
  params:
    - name: script
      description: The script to run
      type: string
  steps:
    - name: kubectl
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        set -e
        $(params.script)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build-and-load
  namespace: lilypad
spec:
  workspaces:
    - name: source
  params:
    - name: image-name
      description: The name of the image to build
      type: string
    - name: image-tag
      description: The tag for the built image
      type: string
    - name: context
      description: The context directory
      type: string
      default: "."
    - name: dockerfile
      description: The path to the Dockerfile
      type: string
      default: "./Dockerfile"
    - name: registry-url
      description: The Docker registry URL
      type: string
      default: "registry:5000"
  steps:
    - name: build-and-load
      image: docker:24.0-dind
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-storage
      script: |
        #!/bin/sh
        set -e
        cd $(workspaces.source.path)/$(params.context)
        
        # Start Docker daemon
        dockerd-entrypoint.sh &
        sleep 10  # Give Docker time to start
        
        # Generate a unique tag with timestamp
        TIMESTAMP=$(date +%s)
        FULL_TAG="$(params.image-tag)-${TIMESTAMP}"
        
        # Build the Docker image
        echo "Building Docker image $(params.image-name):${FULL_TAG}..."
        docker build -t $(params.image-name):${FULL_TAG} -f $(params.dockerfile) .
        
        # Tag with registry URL for pushing
        REGISTRY_IMAGE="$(params.registry-url)/$(params.image-name):${FULL_TAG}"
        REGISTRY_IMAGE_LATEST="$(params.registry-url)/$(params.image-name):latest"
        
        # Tag images with registry URL
        docker tag $(params.image-name):${FULL_TAG} ${REGISTRY_IMAGE}
        docker tag $(params.image-name):${FULL_TAG} ${REGISTRY_IMAGE_LATEST}
        
        # Save the image to a tar file
        echo "Saving image to tar file..."
        docker save ${REGISTRY_IMAGE} ${REGISTRY_IMAGE_LATEST} -o /tmp/image.tar
        
        # Copy the image to minikube
        echo "Transferring image to minikube..."
        # This uses a trick where we output the tar file and the next step can use it
        cat /tmp/image.tar > /workspace/image.tar
        
        # Print success message
        echo "Image built successfully and saved for loading into minikube"
        
    - name: load-to-minikube
      image: bitnami/kubectl:latest
      volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-storage
      script: |
        #!/bin/sh
        set -e
        
        # Transfer the tar to minikube and load it
        echo "Loading image into minikube..."
        
        # Create a helper pod to load the image
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Pod
        metadata:
          name: image-loader
          namespace: lilypad
        spec:
          containers:
          - name: loader
            image: docker:24.0
            command: ["sleep", "600"]
            volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: image-tar
              mountPath: /tmp/image.tar
              subPath: image.tar
          volumes:
          - name: docker-socket
            hostPath:
              path: /var/run/docker.sock
          - name: image-tar
            hostPath:
              path: /workspace/image.tar
        EOF
        
        # Wait for the pod to be ready
        kubectl wait --for=condition=Ready pod/image-loader -n lilypad --timeout=60s
        
        # Load the image in minikube
        echo "Running docker load command in the helper pod..."
        kubectl exec -n lilypad image-loader -- docker load -i /tmp/image.tar
        
        # Verify the image is loaded
        echo "Verifying image is loaded in minikube..."
        kubectl exec -n lilypad image-loader -- docker images | grep $(params.image-name)
        
        # Clean up
        echo "Cleaning up the helper pod..."
        kubectl delete pod image-loader -n lilypad
  volumes:
    - name: docker-storage
      emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-push
  namespace: lilypad
spec:
  workspaces:
    - name: source
  params:
    - name: image-name
      description: The name of the image to push
      type: string
    - name: image-tag
      description: The tag for the image to push
      type: string
    - name: registry-url
      description: The Docker registry URL to push the image to
      type: string
    - name: registry-user
      description: The Docker registry username
      type: string
      default: ""
    - name: registry-password
      description: The Docker registry password
      type: string
      default: ""
  steps:
    - name: push-to-registry
      image: docker:24.0-dind
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-storage
      script: |
        #!/bin/sh
        set -e
        
        # Start Docker daemon
        echo "Starting Docker daemon..."
        dockerd-entrypoint.sh &
        sleep 10  # Give Docker time to start
        
        # Echo parameters for debugging
        echo "Parameters:"
        echo "- Image name: $(params.image-name)"
        echo "- Image tag: $(params.image-tag)"
        echo "- Registry URL: $(params.registry-url)"
        
        # Load the image from the previous step
        echo "Loading Docker image from previous step..."
        docker load -i /workspace/image.tar
        
        # Validate registry URL format
        if [ -z "$(params.registry-url)" ]; then
          echo "ERROR: Registry URL is empty. Please provide a valid registry URL."
          exit 1
        fi
        
        # Registry images should already be tagged correctly in the previous step
        REGISTRY_IMAGE_LATEST="$(params.registry-url)/$(params.image-name):latest"
        
        # Login to the registry if credentials are provided
        if [ -n "$(params.registry-user)" ] && [ -n "$(params.registry-password)" ]; then
          echo "Logging in to Docker registry $(params.registry-url)..."
          echo "$(params.registry-password)" | docker login $(params.registry-url) -u $(params.registry-user) --password-stdin
        else
          echo "No registry credentials provided, assuming local registry access."
        fi
        
        # Push the image to the registry
        echo "Pushing image to registry..."
        docker push ${REGISTRY_IMAGE_LATEST}
        
        # Verify the push
        docker images | grep $(params.registry-url)/$(params.image-name)
        
        echo "Image successfully pushed to registry!"
  volumes:
    - name: docker-storage
      emptyDir: {}
